language: python
python:
  - 3.6
node_js:
  - 10
git:
  depth: 5
services:
  - docker
branches:
  only:
    - master
env:
  - NODE_OPTIONS="--max_old_space_size=4096"
install:
  - python -m pip install --upgrade pip
  - pip install wheel

jobs:
  include:
    - stage: app-build
      script:
        - cd app
        - npm install
        - npm run lint
        - npm run build
        - cd ..
    - stage: api-build
      script:
        - cd api
        - pip install -r requirements.txt
        - python setup.py bdist_wheel
        - cd ..
    - stage: docker-build
      script:
        - docker build -t travis-docker-git-ci-cd:latest .
stages:
  - app-build
  - api-build
  - docker-build
