language: python
python:
  - 3.6
node_js:
  - 10
git:
  depth: 5
services:
  - docker
branches:
  only:
    - master
env:
  - NODE_OPTIONS="--max_old_space_size=4096"
install:
  - bash build.sh install
script:
  - bash build.sh package
  - bash build.sh deploy
  - docker images
deploy:
  provider: script
  script: bash build.sh deploy
